/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package favoritebooks;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author yarkingazibaba
 */
public class AddBookFrame extends javax.swing.JFrame {

    Library library;
    FileHandler fileHandler = new FileHandler();
    ShowBox showBoxAddedBook = new ShowBox();
    
 
    public AddBookFrame(Library library) {
        this.library = library;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        tittleTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        authorNameSurnameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        awardWinnerTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pagesTextField = new javax.swing.JTextField();
        ratingJComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        addBookBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        backToMainPageBtn = new javax.swing.JButton();
        tittleWarning = new javax.swing.JLabel();
        nameAndSurnameWarning = new javax.swing.JLabel();
        categoryWarning = new javax.swing.JLabel();
        awardWarning = new javax.swing.JLabel();
        pagesWarning = new javax.swing.JLabel();
        YearWarning = new javax.swing.JLabel();
        descriptionWarning = new javax.swing.JLabel();
        checkTheFieldsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookAddedArea = new javax.swing.JTextArea();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(74, 31, 61));

        tittleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tittleTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("TITLE");

        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("CATEGORY");

        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("AUTHOR NAME AND SURNAME");

        jLabel4.setForeground(new java.awt.Color(238, 238, 238));
        jLabel4.setText("AWARD WINNER");

        jLabel5.setForeground(new java.awt.Color(238, 238, 238));
        jLabel5.setText("YEAR");

        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setText("NUMBER OF PAGES");

        ratingJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel7.setForeground(new java.awt.Color(238, 238, 238));
        jLabel7.setText("Rating");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        jLabel8.setForeground(new java.awt.Color(238, 238, 238));
        jLabel8.setText("Short book Description");

        addBookBtn.setText("Add Book");
        addBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBtnActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("Add Book Frame");

        backToMainPageBtn.setText("Back To Main Page");
        backToMainPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainPageBtnActionPerformed(evt);
            }
        });

        tittleWarning.setForeground(new java.awt.Color(238, 238, 238));
        tittleWarning.setText("enter the tittle");

        nameAndSurnameWarning.setForeground(new java.awt.Color(238, 238, 238));
        nameAndSurnameWarning.setText("enther the author name and surname");

        categoryWarning.setForeground(new java.awt.Color(238, 238, 238));
        categoryWarning.setText("enter the category");

        awardWarning.setForeground(new java.awt.Color(238, 238, 238));
        awardWarning.setText("enter the award winner");

        pagesWarning.setForeground(new java.awt.Color(238, 238, 238));
        pagesWarning.setText("enter the number of pages");

        YearWarning.setForeground(new java.awt.Color(238, 238, 238));
        YearWarning.setText("enter the year ");

        descriptionWarning.setForeground(new java.awt.Color(238, 238, 238));
        descriptionWarning.setText("enter the short description");

        checkTheFieldsLabel.setForeground(new java.awt.Color(204, 255, 51));

        bookAddedArea.setEditable(false);
        bookAddedArea.setColumns(20);
        bookAddedArea.setForeground(new java.awt.Color(102, 204, 0));
        bookAddedArea.setRows(5);
        bookAddedArea.setText("THE ADDED BOOK INFORMATION\n            DISPLAYS IN HERE ");
        jScrollPane2.setViewportView(bookAddedArea);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToMainPageBtn)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(504, 504, 504))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descriptionWarning)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearTextField)
                                    .addComponent(authorNameSurnameTextField)
                                    .addComponent(categoryTextField)
                                    .addComponent(tittleTextField)
                                    .addComponent(awardWinnerTextField)
                                    .addComponent(pagesTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pagesWarning)
                                    .addComponent(tittleWarning)
                                    .addComponent(nameAndSurnameWarning)
                                    .addComponent(awardWarning)
                                    .addComponent(categoryWarning)
                                    .addComponent(YearWarning)))
                            .addComponent(ratingJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(addBookBtn)
                .addGap(365, 365, 365)
                .addComponent(checkTheFieldsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backToMainPageBtn)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tittleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tittleWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(categoryWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(authorNameSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameAndSurnameWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(awardWinnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(awardWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(YearWarning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pagesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pagesWarning)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ratingJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(descriptionWarning))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTheFieldsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(addBookBtn)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tittleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tittleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tittleTextFieldActionPerformed

    private void backToMainPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainPageBtnActionPerformed

            MainPage mainPage = new MainPage(library);
            this.setVisible(false);
            mainPage.setVisible(true);
            mainPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);         
    }//GEN-LAST:event_backToMainPageBtnActionPerformed

    private void addBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBtnActionPerformed
        
       
        String titleField = tittleTextField.getText();
        String categoryField = categoryTextField.getText().toLowerCase();
        String authorNameSurnameField = authorNameSurnameTextField.getText();
        String awardWinnerField = awardWinnerTextField.getText();
        String yearField = yearTextField.getText();
        String numberOfPagesField = pagesTextField.getText();
        int rating = ratingJComboBox.getItemCount();
        String descriptionText = descriptionTextArea.getText();
        
        
        
 
        
        if(descriptionText.equals("") || titleField.equals("") || categoryField.equals("") || authorNameSurnameField.equals("") ||awardWinnerField.equals("")|| yearField.equals("") ||numberOfPagesField.equals("")) {
                showBoxAddedBook.infoBox("check the fields and Please enter proper informations", "Book Does not Added");
                checkTheFieldsLabel.getText();
                checkTheFieldsLabel.setText("check the fields and book is not added");
            
        } else{
                
            Book lastBook = library.getBookListInLibrary().get(library.getBookListInLibrary().size()- 1);
            int autoIdGenerator = lastBook.bookId + 1;

            int numericYearField = Integer.parseInt(yearField); // data comes string frome the add Book frame we are parsing to integer
            int numericNumberOfPages = Integer.parseInt(numberOfPagesField);// data comes string frome the add Book frame we are parsing to integer// data comes string frome the add Book frame we are parsing to integer
            
            Book book = new Book(autoIdGenerator,titleField,categoryField,authorNameSurnameField,awardWinnerField,rating,numericYearField,numericNumberOfPages,descriptionText);
           
            library.addBookToLibrary(book);
            try {
                fileHandler.appendBookToFile(book);
            } catch (IOException ex) {
                Logger.getLogger(AddBookFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            //String tittle, String category, String authorNameAndSurname,String awardWinner,int rating,int year,int numberOfPages, String shortDescription){
            
            checkTheFieldsLabel.getText();
            checkTheFieldsLabel.setText("");
            checkTheFieldsLabel.setText("The book has been added to the system");

            String previousText = bookAddedArea.getText();
            bookAddedArea.setText(previousText + "\n" + book.toString());
            
            showBoxAddedBook.infoBox("The book added to list : " + book.toString(), "Book Adding");
            
            tittleTextField.setText("");
            categoryTextField.setText("");
            authorNameSurnameTextField.setText("");
            awardWinnerTextField.setText("");
            yearTextField.setText("");
            pagesTextField.setText("");
            descriptionTextArea.setText("");
                
        }        
    }//GEN-LAST:event_addBookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel YearWarning;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JTextField authorNameSurnameTextField;
    private javax.swing.JLabel awardWarning;
    private javax.swing.JTextField awardWinnerTextField;
    private javax.swing.JButton backToMainPageBtn;
    private javax.swing.JTextArea bookAddedArea;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JLabel categoryWarning;
    private javax.swing.JLabel checkTheFieldsLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel descriptionWarning;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameAndSurnameWarning;
    private javax.swing.JTextField pagesTextField;
    private javax.swing.JLabel pagesWarning;
    private javax.swing.JComboBox<String> ratingJComboBox;
    private javax.swing.JTextField tittleTextField;
    private javax.swing.JLabel tittleWarning;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
